models:
- provider: OpenAI
  id: gpt-5-2025-08-07
  enabled: false
  api_key_env: OPENAI_API_KEY
  standard_name: gpt-5
  link: https://platform.openai.com/docs/models/gpt-5
- provider: OpenAI
  id: gpt-5-mini-2025-08-07
  enabled: false
  api_key_env: OPENAI_API_KEY
  standard_name: gpt-5-mini
  link: https://platform.openai.com/docs/models/gpt-5-mini
- provider: OpenAI
  id: gpt-5-nano-2025-08-07
  enabled: false
  api_key_env: OPENAI_API_KEY
  standard_name: gpt-5-nano
  link: https://platform.openai.com/docs/models/gpt-5-nano
- provider: OpenAI
  id: gpt-4.1-2025-04-14
  enabled: false
  api_key_env: OPENAI_API_KEY
  standard_name: gpt-4.1
  link: https://platform.openai.com/docs/models/gpt-4.1
- provider: OpenAI
  id: o4-mini-2025-04-16
  enabled: false
  api_key_env: OPENAI_API_KEY
  standard_name: o4-mini
  link: https://platform.openai.com/docs/models/o4-mini
- provider: OpenAI
  id: o3-pro-2025-06-10
  enabled: false
  api_key_env: OPENAI_API_KEY
  standard_name: o3-pro
  link: https://platform.openai.com/docs/models/o3-pro
- provider: OpenAI
  id: o3-2025-04-16
  enabled: false
  api_key_env: OPENAI_API_KEY
  standard_name: o3
  link: https://platform.openai.com/docs/models/o3
- provider: OpenAI
  id: gpt-4o
  enabled: false
  api_key_env: OPENAI_API_KEY
  standard_name: gpt-4o
  link: https://platform.openai.com/docs/models/gpt-4o
- provider: Google
  id: gemini-2.5-flash
  enabled: false
  api_key_env: GOOGLE_API_KEY
  standard_name: gemini-2.5-flash
  link: https://ai.google.dev/gemini-api/docs/models?hl=it#gemini-2.5-flash
- provider: Google
  id: gemini-2.5-pro
  enabled: false
  api_key_env: GOOGLE_API_KEY
  standard_name: gemini-2.5-pro
  link: https://ai.google.dev/gemini-api/docs/models?hl=it#gemini-2.5-pro
- provider: Google
  id: gemini-2.0-flash
  enabled: false
  api_key_env: GOOGLE_API_KEY
  standard_name: gemini-2.0-flash
  link: https://ai.google.dev/gemini-api/docs/models?hl=it#gemini-2.0-flash
- provider: Mistral
  id: mistral-small-2506
  enabled: false
  api_key_env: MISTRAL_API_KEY
  standard_name: mistral-small
  link: https://docs.mistral.ai/getting-started/models/models_overview/
- provider: Mistral
  id: mistral-medium-2508
  enabled: false
  api_key_env: MISTRAL_API_KEY
  standard_name: mistral-medium-3.1
  link: https://docs.mistral.ai/getting-started/models/models_overview/
- provider: Groq
  id: meta-llama/llama-4-scout-17b-16e-instruct
  enabled: false
  api_key_env: GROQ_API_KEY
  standard_name: llama-4-scout-17b
  link: https://console.groq.com/docs/model/meta-llama/llama-4-scout-17b-16e-instruct
- provider: Groq
  id: meta-llama/llama-4-maverick-17b-128e-instruct
  enabled: false
  api_key_env: GROQ_API_KEY
  standard_name: llama-4-maverick-17b
  link: https://console.groq.com/docs/model/meta-llama/llama-4-maverick-17b-128e-instruct
- provider: Anthropic
  id: claude-opus-4-20250514
  enabled: false
  api_key_env: ANTHROPIC_API_KEY
  standard_name: claude-4-opus
  link: https://docs.anthropic.com/en/docs/about-claude/models/overview
- provider: Anthropic
  id: claude-sonnet-4-20250514
  enabled: false
  api_key_env: ANTHROPIC_API_KEY
  standard_name: claude-4-sonnet
  link: https://docs.anthropic.com/en/docs/about-claude/models/overview
- provider: Anthropic
  id: claude-3-7-sonnet-20250219
  enabled: false
  api_key_env: ANTHROPIC_API_KEY
  standard_name: claude-3.7-sonnet
  link: https://docs.anthropic.com/en/docs/about-claude/models/overview
- provider: xAI
  id: grok-4-0709
  enabled: false
  api_key_env: XAI_API_KEY
  standard_name: grok-4
  link: https://docs.x.ai/docs/overview
- provider: xAI
  id: grok-2-vision-1212
  enabled: false
  api_key_env: XAI_API_KEY
  standard_name: grok-2-vision
  link: https://docs.x.ai/docs/overview
- provider: OpenRouter
  id: arcee-ai/spotlight
  enabled: false
  api_key_env: OPENROUTER_API_KEY
  standard_name: spotlight
  link: https://openrouter.ai/arcee-ai/spotlight
- provider: OpenRouter
  id: mistralai/mistral-small-3.2-24b-instruct:free
  enabled: false
  api_key_env: OPENROUTER_API_KEY
  standard_name: mistral-small
- provider: OpenRouter
  id: moonshotai/kimi-vl-a3b-thinking:free
  enabled: false
  api_key_env: OPENROUTER_API_KEY
  standard_name: kimi-vl-a3b-thinking
  link: https://openrouter.ai/moonshotai/kimi-vl-a3b-thinking:free
- provider: OpenRouter
  id: qwen/qwen2.5-vl-72b-instruct:free
  enabled: false
  api_key_env: OPENROUTER_API_KEY
  standard_name: qwen-2.5-vl-72b
  link: https://openrouter.ai/qwen/qwen2.5-vl-72b-instruct:free
- provider: OpenRouter
  id: z-ai/glm-4.5v
  enabled: false
  api_key_env: OPENROUTER_API_KEY
  standard_name: glm-4.5v
  link: https://openrouter.ai/z-ai/glm-4.5v
- provider: OpenRouter
  id: baidu/ernie-4.5-vl-28b-a3b
  enabled: false
  api_key_env: OPENROUTER_API_KEY
  standard_name: ernie-4.5-vl-28b-a3b
  link: https://openrouter.ai/baidu/ernie-4.5-vl-28b-a3b
- provider: OpenRouter
  id: stepfun-ai/step3
  enabled: false
  api_key_env: OPENROUTER_API_KEY
  standard_name: step3s
  link: https://openrouter.ai/stepfun-ai/step3
- provider: OpenRouter
  id: deepcogito/cogito-v2-preview-llama-109b-moe
  enabled: true
  api_key_env: OPENROUTER_API_KEY
  standard_name: cogito-v2-109b
  link: https://openrouter.ai/deepcogito/cogito-v2-preview-llama-109b-moe
- provider: OpenRouter
  id: openrouter/sonoma-sky-alpha
  enabled: false
  api_key_env: OPENROUTER_API_KEY
  standard_name: sonoma-sky-alpha
  link: https://openrouter.ai/openrouter/sonoma-sky-alpha
- provider: OpenRouter
  id: openrouter/sonoma-dusk-alpha
  enabled: false
  api_key_env: OPENROUTER_API_KEY
  standard_name: sonoma-dusk-alpha
  link: https://openrouter.ai/openrouter/sonoma-dusk-alpha
- provider: Nebius
  id: Qwen/Qwen2.5-VL-72B-Instruct
  enabled: false
  api_key_env: NEBIUS_API_KEY
  standard_name: qwen-2.5-vl-72b
